export const Users = [
    {
        id:1,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
    {
        id:2,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
    {
        id:3,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
    {
        id:4,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
    {
        id:5,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
    {
        id:6,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
    {
        id:7,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
    {
        id:8,
        profilePicture: "assets/person/headshot.jpg",
        username: "Jared Martin",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 2,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 4,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 5,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 6,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 7,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 8,
        desc: "One for all and All for one!",
        photo: "assets/post/headshot.jpg",
        date: "15 mins Ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
]